"use client";
import {useState} from 'react';
export default function Access(){
 const [mode,setMode]=useState<'ingresar'|'registrar'>('ingresar');const [nombre,setNombre]=useState(''),[clave,setClave]=useState(''),[codigo,setCodigo]=useState('');
 const [owner,setOwner]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
 const r=await fetch(`/api/acceso/${mode==='ingresar'?'entrar':'registrar'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nombre,clave,codigo:owner?codigo:''})});
 const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'No se pudo continuar.');window.location.replace('/');
 }catch(e){setError((e as Error).message);setBusy(false)}}
 return <main className="access-screen"><section className="access-card"><span className="overline">BABY CREYSI · CONTROL ADMINISTRATIVO</span><h1>Sistema de control documental y administrativo</h1><p>Registra y consulta facturas de proveedores y documentos desde un solo lugar.</p><div className="auth-tabs"><button type="button" className={mode==='ingresar'?'selected':''} onClick={()=>{setMode('ingresar');setError('')}}>Iniciar sesión</button><button type="button" className={mode==='registrar'?'selected':''} onClick={()=>{setMode('registrar');setError('')}}>Crear cuenta</button></div><form onSubmit={submit}><label>Nombre completo<input required autoComplete="name" value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Nombre y apellidos"/></label><label>Contraseña<input required type="password" minLength={mode==='registrar'?12:undefined} autoComplete={mode==='registrar'?'new-password':'current-password'} value={clave} onChange={e=>setClave(e.target.value)} placeholder={mode==='registrar'?'Mínimo 12 caracteres':'Tu contraseña'}/></label>{mode==='registrar'&&<><label className="owner-check"><input type="checkbox" checked={owner} onChange={e=>setOwner(e.target.checked)}/> Soy la propietaria</label>{owner&&<label>Código de activación<input required type="password" value={codigo} onChange={e=>setCodigo(e.target.value)} placeholder="Código privado de la propietaria"/></label>}</>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Espera…':mode==='ingresar'?'Entrar':'Crear cuenta y entrar'}</button></form><p className="access-note">{mode==='registrar'?'Usa tu nombre completo para volver a iniciar sesión.':'¿Primera vez? Selecciona Crear cuenta.'}</p></section></main>
}
