"use client";
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ChevronLeft,ChevronRight,Download,FileText,Plus,X,Pencil,Check,Trash2,LogOut,ClipboardList } from 'lucide-react';

type Provider={id:number;nombre:string;rfc:string};
type Invoice={id:number;folio:string;proveedorId:number;proveedor:string;rfc:string;fechaEmision:string;subtotal:number|null;concepto:string;impuestoPct:number;idFiscal:string;total:number;registradoEn:string;registradoPor:string;estado:string;observaciones:string};
type Document={id:number;tipo:string;titulo:string;referencia:string;fecha:string;ubicacion:string;observaciones:string};
type Event={id:number;accion:string;folio:string;detalle:string;persona:string;fecha:string};
type Draft={folio:string;fechaEmision:string;proveedorNombre:string;idFiscal:string;concepto:string;subtotal:string;impuestoPct:string;estado:string;observaciones:string};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Mexico_City'});
const blank=():Draft=>({folio:'',fechaEmision:today(),proveedorNombre:'',idFiscal:'',concepto:'',subtotal:'',impuestoPct:'0',estado:'Pendiente',observaciones:''});
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
const dateText=(s:string)=>s?new Date(s.slice(0,10)+'T12:00:00Z').toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'—';
const dateTime=(s:string)=>s?new Date(s).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'}):'—';
const shiftDate=(s:string,delta:number)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);return d.toISOString().slice(0,10)};
export default function Dashboard({userName,role}:{userName:string;role:string}){
 const [tab,setTab]=useState<'facturas'|'bitacora'|'documentos'>('facturas');
 const [range,setRange]=useState<'dia'|'todos'>('dia');const [day,setDay]=useState(today());
 const [invoices,setInvoices]=useState<Invoice[]>([]),[providers,setProviders]=useState<Provider[]>([]),[documents,setDocuments]=useState<Document[]>([]),[events,setEvents]=useState<Event[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const [form,setForm]=useState<Draft|null>(null),[editing,setEditing]=useState<number|null>(null);
 const [docForm,setDocForm]=useState(false),[docDraft,setDocDraft]=useState({tipo:'Acta',titulo:'',referencia:'',fecha:'',ubicacion:'',observaciones:''});
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/data',{cache:'no-store'});const d=await r.json() as {error?:string;facturas:Invoice[];proveedores:Provider[];documentos:Document[];bitacora:Event[]};if(!r.ok)throw new Error(d.error||'No se pudieron cargar los registros.');setInvoices(d.facturas);setProviders(d.proveedores);setDocuments(d.documentos);setEvents(d.bitacora);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const visible=useMemo(()=>invoices.filter(f=>range==='todos'||f.fechaEmision===day),[invoices,range,day]);
 const total=visible.filter(f=>f.estado!=='Cancelada').reduce((n,f)=>n+(Number(f.total)||0),0);
 const pending=visible.filter(f=>f.estado==='Pendiente').length;
 async function mutate(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'No se pudo guardar.');}
 function start(){setEditing(null);setForm(blank());setError('')}
 function edit(f:Invoice){setEditing(f.id);setForm({folio:f.folio,fechaEmision:f.fechaEmision,proveedorNombre:f.proveedor,idFiscal:f.idFiscal||'',concepto:f.concepto||'',subtotal:f.subtotal==null?'':String(f.subtotal),impuestoPct:String(f.impuestoPct||0),estado:f.estado,observaciones:f.observaciones||''});setError('')}
 async function saveInvoice(e:React.FormEvent){e.preventDefault();if(!form)return;setSaving(true);setError('');try{await mutate(editing?`/api/facturas/${editing}`:'/api/facturas',editing?'PUT':'POST',{...form,subtotal:Number(form.subtotal),impuestoPct:Number(form.impuestoPct)});setForm(null);setNotice(editing?'Factura actualizada.':'Factura registrada.');await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function paid(f:Invoice){setSaving(true);setError('');try{await mutate(`/api/facturas/${f.id}/pagada`,'POST');setNotice(`${f.folio} marcada como pagada.`);await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function remove(f:Invoice){if(!confirm(`¿Eliminar la factura ${f.folio}? No se puede deshacer.`))return;setSaving(true);setError('');try{await mutate(`/api/facturas/${f.id}`,'DELETE');setNotice('Factura eliminada.');await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveDocument(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await mutate('/api/documentos','POST',docDraft);setDocForm(false);setDocDraft({tipo:'Acta',titulo:'',referencia:'',fecha:'',ubicacion:'',observaciones:''});setNotice('Documento registrado.');await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function signOut(){try{await fetch('/api/acceso/salir',{method:'POST'})}finally{window.location.replace('/')}}
 const calculated=form?Math.round((Number(form.subtotal)||0)*(1+(Number(form.impuestoPct)||0)/100)*100)/100:0;
 return <div className="ledger-app"><header className="ledger-header"><div className="ledger-brand"><span className="logo-box">BC</span><span><strong>Baby Creysi</strong><small>Control documental</small></span></div><div className="ledger-account"><strong>{userName.toLocaleUpperCase('es-MX')}</strong><span>{role==='propietario'?'Propietaria':'Usuario'}</span><button onClick={signOut}>Salir <LogOut size={15}/></button></div></header><main className="ledger-main">
  <div className="ledger-tabs"><button className={tab==='facturas'?'active':''} onClick={()=>setTab('facturas')}>Facturas</button><button className={tab==='bitacora'?'active':''} onClick={()=>setTab('bitacora')}>Bitácora</button><button className={tab==='documentos'?'active':''} onClick={()=>setTab('documentos')}>Documentos</button></div>
  {error&&<div role="alert" className="ledger-alert error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div role="status" className="ledger-alert success">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  {tab==='facturas'&&<><div className="ledger-toolbar"><div className="segmented"><button className={range==='dia'?'active':''} onClick={()=>setRange('dia')}>Del día</button><button className={range==='todos'?'active':''} onClick={()=>setRange('todos')}>Todos</button></div><div className="toolbar-actions"><a className="outlined" href="/api/exportar"><Download size={17}/> Exportar archivo</a><button className="pink-button" onClick={start}><Plus size={17}/> Registrar factura</button></div></div>{range==='dia'&&<div className="date-controls"><button aria-label="Día anterior" onClick={()=>setDay(shiftDate(day,-1))}><ChevronLeft size={19}/></button><input aria-label="Fecha de consulta" type="date" value={day} onChange={e=>setDay(e.target.value)}/><button aria-label="Día siguiente" onClick={()=>setDay(shiftDate(day,1))}><ChevronRight size={19}/></button><button onClick={()=>setDay(today())}>Hoy</button></div>}
   <div className="ledger-summary"><p><strong>{visible.length} {visible.length===1?'factura':'facturas'} por un total de {money(total)}</strong> <span>sin contar anuladas</span></p>{pending>0&&<span className="summary-pending">Pendiente: {pending}</span>}</div>
   {loading?<div className="ledger-empty">Cargando registros…</div>:visible.length?visible.map(f=><article className="invoice-card" key={f.id}><div className="invoice-info"><span className="invoice-number">{f.folio}</span><h2>{f.proveedor}</h2><p>{f.concepto||'Sin concepto registrado'}</p><dl><div><dt>Fecha de emisión</dt><dd>{dateText(f.fechaEmision)}</dd></div><div><dt>Registrado</dt><dd>{dateTime(f.registradoEn)}</dd></div><div><dt>Registró</dt><dd>{f.registradoPor||'—'}</dd></div><div><dt>ID fiscal</dt><dd>{f.idFiscal||'—'}</dd></div></dl></div><div className="invoice-right"><strong className="invoice-total">{money(Number(f.total)||0)}</strong><small>Subtotal {f.subtotal==null?'—':money(f.subtotal)}, impuesto {f.impuestoPct||0}%</small><span className={`invoice-state state-${f.estado.toLowerCase()}`}>{f.estado}</span><div className="invoice-buttons"><button onClick={()=>edit(f)}><Pencil size={15}/> Editar</button>{f.estado==='Pendiente'&&<button onClick={()=>paid(f)} disabled={saving}><Check size={15}/> Marcar pagada</button>}<button className="delete-btn" onClick={()=>remove(f)} disabled={saving} aria-label={`Eliminar ${f.folio}`}><Trash2 size={15}/></button></div></div></article>):<div className="ledger-empty"><FileText size={28}/><strong>No hay facturas en esta vista</strong><p>{range==='dia'?'Elige otra fecha o selecciona Todos para consultar los registros.':'Registra la primera factura para comenzar.'}</p></div>}</>}
  {tab==='bitacora'&&<><div className="ledger-section-head"><div><h1>Bitácora</h1><p>Movimientos de facturas y persona responsable.</p></div></div>{events.length?events.map(ev=><article className="event-row" key={ev.id}><span className="event-dot"/><div><strong>{ev.accion} · {ev.folio}</strong><p>{ev.detalle}</p></div><div className="event-meta">{ev.persona}<small>{dateTime(ev.fecha)}</small></div></article>):<div className="ledger-empty"><ClipboardList size={28}/>Todavía no hay movimientos.</div>}</>}
  {tab==='documentos'&&<><div className="ledger-section-head"><div><h1>Documentos y actas</h1><p>Registra una referencia y la ubicación del archivo físico. La carga de PDF se añadirá más adelante.</p></div>{role==='propietario'&&<button className="pink-button" onClick={()=>setDocForm(true)}><Plus size={17}/> Nuevo documento</button>}</div>{documents.length?documents.map(d=><article className="document-row" key={d.id}><span className="invoice-number">{d.tipo}</span><h2>{d.titulo}</h2><p>Referencia: {d.referencia||'—'} · Fecha: {dateText(d.fecha)} · Ubicación: {d.ubicacion||'—'}</p>{d.observaciones&&<small>{d.observaciones}</small>}</article>):<div className="ledger-empty"><FileText size={28}/>Todavía no hay documentos registrados.</div>}</>}
 </main>
 {form&&<div className="ledger-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setForm(null)}}><section className="ledger-modal" role="dialog" aria-modal="true" aria-labelledby="invoice-modal-title"><header><h2 id="invoice-modal-title">{editing?'Editar factura':'Registrar factura'}</h2><button aria-label="Cerrar" onClick={()=>setForm(null)}><X size={22}/></button></header><form onSubmit={saveInvoice}><div className="modal-scroll"><div className="modal-grid"><label>Número de factura<input required maxLength={80} value={form.folio} onChange={e=>setForm({...form,folio:e.target.value})}/></label><label>Fecha de emisión<input required type="date" value={form.fechaEmision} onChange={e=>setForm({...form,fechaEmision:e.target.value})}/></label><label>Proveedor<input required maxLength={150} list="proveedores-sugeridos" value={form.proveedorNombre} onChange={e=>setForm({...form,proveedorNombre:e.target.value})}/><datalist id="proveedores-sugeridos">{providers.map(p=><option key={p.id} value={p.nombre}/>)}</datalist></label><label>ID fiscal (opcional)<input maxLength={100} value={form.idFiscal} onChange={e=>setForm({...form,idFiscal:e.target.value})}/></label><label className="full">Concepto<input required maxLength={300} value={form.concepto} onChange={e=>setForm({...form,concepto:e.target.value})}/></label><div className="tax-row"><label>Subtotal<input type="number" step="0.01" min="0" max="99999999999" required placeholder="0.00" value={form.subtotal} onChange={e=>setForm({...form,subtotal:e.target.value})}/></label><label>Impuesto (%)<input type="number" step="0.01" min="0" max="100" required value={form.impuestoPct} onChange={e=>setForm({...form,impuestoPct:e.target.value})}/></label><div className="total-preview"><span>Total</span><strong>{money(calculated)}</strong></div></div><label className="full">Estado<select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}><option>Pendiente</option><option>Pagada</option><option>Cancelada</option></select></label><label className="full">Observaciones (opcional)<textarea rows={3} maxLength={1000} value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label></div></div><footer><button type="button" className="outlined" onClick={()=>setForm(null)}>Cancelar</button><button className="pink-button" disabled={saving}>{saving?'Guardando…':'Guardar'}</button></footer></form></section></div>}
 {docForm&&role==='propietario'&&<div className="ledger-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDocForm(false)}}><section className="ledger-modal" role="dialog" aria-modal="true" aria-labelledby="doc-modal-title"><header><h2 id="doc-modal-title">Registrar documento</h2><button aria-label="Cerrar" onClick={()=>setDocForm(false)}><X size={22}/></button></header><form onSubmit={saveDocument}><div className="modal-scroll"><div className="modal-grid"><label>Tipo<select value={docDraft.tipo} onChange={e=>setDocDraft({...docDraft,tipo:e.target.value})}>{['Acta','Escritura','Poder','Contrato','Fiscal','Otro'].map(t=><option key={t}>{t}</option>)}</select></label><label>Fecha<input type="date" value={docDraft.fecha} onChange={e=>setDocDraft({...docDraft,fecha:e.target.value})}/></label><label className="full">Título<input required maxLength={180} value={docDraft.titulo} onChange={e=>setDocDraft({...docDraft,titulo:e.target.value})}/></label><label>Referencia<input maxLength={100} value={docDraft.referencia} onChange={e=>setDocDraft({...docDraft,referencia:e.target.value})}/></label><label>Ubicación física<input maxLength={180} value={docDraft.ubicacion} onChange={e=>setDocDraft({...docDraft,ubicacion:e.target.value})}/></label><label className="full">Observaciones<textarea rows={3} maxLength={1000} value={docDraft.observaciones} onChange={e=>setDocDraft({...docDraft,observaciones:e.target.value})}/></label></div></div><footer><button type="button" className="outlined" onClick={()=>setDocForm(false)}>Cancelar</button><button className="pink-button" disabled={saving}>Guardar</button></footer></form></section></div>}
 </div>
}
